<!-- 
    /* ------------- Arquivo que é chamada pelo HomeController do diretorio Controllores ------------ */ 
-->
<div class="container row-bottom-20">
    <div class="row">
        <h2 class="h2"><?= $this->getPageTitle();?></h2>    
    </div>
    <div class="row">
        <div class="col-xl-12 col-xl-offset-1 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">Dog developer Micro Framework</h1>
            <p>
                Este é um micro framework MVC em PHP, construíndo como exercício do conteúdo didático do
                curso "Micro Framework do Zero" disponibilizado no canal TJG Web no Youtube. 
            </p>
            <p>
                O intúito do curso é exclarecer os conceitos e o funcionamento dos grandes frameworks de 
                renome já consagrados hoje no mercado. Depois esse curso o aluno entenderá melhor os
                cursos oferecidos na internet de framework como Laravel, Zend, CakePHP, etc.
            </p>
        </div>
    </div>
</div>